import type { Program } from "./types";

export const programs: Program[] = [
  {
    id: "aitu-cs",
    university: "Astana IT University",
    shortName: "AITU",
    program: "Computer Science & Software",
    code: "6B06101",
    city: "Астана",
    duration: "3 года",
    language: "Английский",
    interests: ["computer-science", "software-engineering", "cloud-devops"],
    untCombinations: ["Математика + Информатика"],
    highlights: ["Machine Learning", "Cloud & Web services", "Интенсивная 3-летняя программа", "Партнёрство с EPAM"],
    tuitionKzt: 2_500_000,
    tuitionLabel: "2 500 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 80,
    untGrant: 102,
    gpaMinimum: 3.2,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Госгранты МОН РК по группе B057 + ректорские гранты для олимпиадников",
    livingCostEstimateKzt: 180_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Территория EXPO, высокотехнологичные лаборатории, студенческий дом на территории",
    employmentRate: "93% в течение 6 месяцев после выпуска",
    acceptanceRateEstimate: "Конкурс на грант ~6.4 человека на место",
    reviews: [
      { author: "Алишер Б.", course: "3 курс CS", quote: "Сильная нагрузка по алгоритмам и проектам, учимся на реальных стеках. 3 года пролетают очень плотно.", rating: 5 },
      { author: "Динара М.", course: "Выпускница 2025", quote: "Язык обучения реально английский, преподают практики из IT индустрии.", rating: 4.8 }
    ],
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика", description: "Порог 80 для договора, от 102 на конкурс грантов", isMandatory: true },
      { label: "Английский язык", description: "IELTS 5.0+ либо сдача AET в кампусе", isMandatory: true },
      { label: "Аттестат с GPA от 3.0", description: "Оригинал с приложением", isMandatory: true },
      { label: "Медицинская справка 075/у", description: "С флюорографией", isMandatory: true },
    ],
    careerFocus: ["Big Tech & Релокейт", "Стартапы & Astana Hub", "Удалёнка на США/Европу"],
    source: { label: "AITU — Bachelor’s Degree", url: "https://astanait.edu.kz/en/bachelor" },
    requirementsSource: { label: "AITU — Computer Science", url: "https://astanait.edu.kz/Computer-Science-bachelor" },
    dataNote: "Порог на грант — 100-104. Платное обучение: порог ЕНТ 80 и входной тест AET.",
  },
  {
    id: "aitu-big-data",
    university: "Astana IT University",
    shortName: "AITU",
    program: "Big Data & Artificial Intelligence",
    code: "6B06103",
    city: "Астана",
    duration: "3 года",
    language: "Английский",
    interests: ["data-science", "ai-robotics", "fintech"],
    untCombinations: ["Математика + Информатика"],
    highlights: ["Data Engineering", "Deep Learning", "Applied Math", "Серверный кластер GPU"],
    tuitionKzt: 2_500_000,
    tuitionLabel: "2 500 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 80,
    untGrant: 106,
    gpaMinimum: 3.3,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Гранты МОН РК по группе B057, корпоративные стипендии Halyk Bank и Kaspi",
    livingCostEstimateKzt: 180_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Expo Park AITU, серверные лаборатории анализа данных и ИИ",
    employmentRate: "95% трудоустройство",
    acceptanceRateEstimate: "Конкурс на грант ~7.2 человека на место",
    reviews: [
      { author: "Темирлан К.", course: "2 курс Data Science", quote: "Много матана и статистики, но с первого курса работаешь с Python, PyTorch и SQL.", rating: 4.9 }
    ],
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика", description: "Порог 80, для гранта 106+", isMandatory: true },
      { label: "Тест AET или IELTS 5.0+", description: "Проверка базового технического английского", isMandatory: true },
    ],
    careerFocus: ["Big Tech & Релокейт", "Финтех & Банки (Kaspi/Halyk)", "Наука & R&D (ИИ лаборатории)"],
    source: { label: "AITU — Bachelor’s Degree", url: "https://astanait.edu.kz/en/bachelor" },
  },
  {
    id: "aitu-cyber",
    university: "Astana IT University",
    shortName: "AITU",
    program: "Cybersecurity & Network Defense",
    code: "6B06301",
    city: "Астана",
    duration: "3 года",
    language: "Английский",
    interests: ["cybersecurity", "cloud-devops"],
    untCombinations: ["Математика + Информатика"],
    highlights: ["Cyber Range полигон", "SOC лаборатория", "Network forensics", "CTF команда"],
    tuitionKzt: 2_500_000,
    tuitionLabel: "2 500 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 80,
    untGrant: 110,
    gpaMinimum: 3.2,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Высокая квота целевых грантов МОН РК по группе B058",
    livingCostEstimateKzt: 180_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "SOC-центр AITU и закрытый полигон кибератак",
    employmentRate: "96% трудоустройство",
    reviews: [
      { author: "Арсен Т.", course: "Выпускник", quote: "Спрос на инженеров ИБ сумасшедший. Уже на 3 курсе совмещал с работой в банке.", rating: 5.0 }
    ],
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика", description: "Мин. 80 баллов для договора", isMandatory: true },
      { label: "AET/IELTS", description: "Проверка английского", isMandatory: true },
    ],
    careerFocus: ["Кибербезопасность & SOC", "Финтех & Банки (Kaspi/Halyk)", "Big Tech & Релокейт"],
    source: { label: "AITU — Bachelor’s Degree", url: "https://astanait.edu.kz/en/bachelor" },
  },
  {
    id: "kbtu-se",
    university: "Kazakh-British Technical University",
    shortName: "КБТУ",
    program: "Software Engineering & Architecture",
    code: "6B06102",
    city: "Алматы",
    duration: "4 года",
    language: "Английский",
    interests: ["software-engineering", "computer-science", "fintech", "cloud-devops"],
    untCombinations: ["Математика + Информатика", "Математика + Физика"],
    highlights: ["Silicon Valley Network", "Топовые выпускники в Google/Meta/Amazon", "Британские академические стандарты"],
    tuitionKzt: 2_950_000,
    tuitionLabel: "≈ 2 950 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "demo",
    untPaid: 75,
    untGrant: 115,
    gpaMinimum: 3.5,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Гранты МОН РК, стипендии выпускников КБТУ и партнерские стипендии Kaspi.kz/Tengizchevroil",
    livingCostEstimateKzt: 200_000,
    applicationDeadlineEstimate: "до 15 июля 2027",
    campusInfo: "Историческое здание Дома Правительства, Толе би 59, центр Алматы",
    employmentRate: "98% трудоустройство",
    acceptanceRateEstimate: "Высокая селективность, IELTS 5.5+ обязателен",
    reviews: [
      { author: "Айбек Ж.", course: "4 курс SE", quote: "Комьюнити КБТУ — это главный плюс. Все вокруг олимпиадники и хакатонщики, нетворкинг невероятный.", rating: 5.0 }
    ],
    requirementsChecklist: [
      { label: "ЕНТ: Мат+Инф или Мат+Физ", description: "Мин. 75 для платного, от 115 на грант", isMandatory: true },
      { label: "IELTS 5.5+ или экзамен КБТУ", description: "Сдача в приёмной комиссии", isMandatory: true },
      { label: "Аттестат с GPA от 3.3", description: "Выписка оценок", isMandatory: true },
    ],
    careerFocus: ["Big Tech & Релокейт", "Удалёнка на США/Европу", "Финтех & Банки (Kaspi/Halyk)", "Стартапы & Astana Hub"],
    source: { label: "KBTU — Software Engineering", url: "https://kbtu.edu.kz/ru/" },
  },
  {
    id: "kbtu-gamedev",
    university: "Kazakh-British Technical University",
    shortName: "КБТУ",
    program: "Game Development & 3D Interactive Media",
    code: "6B06105",
    city: "Алматы",
    duration: "4 года",
    language: "Английский",
    interests: ["gamedev", "computer-science", "ui-ux-product"],
    untCombinations: ["Математика + Информатика", "Математика + Физика"],
    highlights: ["Unreal Engine 5", "Unity", "3D Rendering & Shaders", "Игровой инкубатор GameLab"],
    tuitionKzt: 2_950_000,
    tuitionLabel: "≈ 2 950 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "demo",
    untPaid: 75,
    untGrant: 112,
    gpaMinimum: 3.3,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Гранты МОН РК + спонсорские гранты международных студий разработки",
    livingCostEstimateKzt: 200_000,
    applicationDeadlineEstimate: "до 15 июля 2027",
    campusInfo: "Кампус КБТУ, GameLab с VR гарнитурами и графическими станциями RTX",
    employmentRate: "94% трудоустройство в gamedev студии мира и РК",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика/Физика", description: "От 75 баллов", isMandatory: true },
      { label: "IELTS 5.5+", description: "Официальный сертификат", isMandatory: true },
    ],
    careerFocus: ["Геймдев & Креатив", "Удалёнка на США/Европу", "Стартапы & Astana Hub"],
    source: { label: "KBTU — GameLab", url: "https://kbtu.edu.kz/" },
  },
  {
    id: "iitu-is",
    university: "International Information Technology University",
    shortName: "МУИТ",
    program: "Information Systems & Enterprise IT",
    code: "B057",
    city: "Алматы",
    duration: "4 года",
    language: "Казахский / русский",
    interests: ["information-systems", "software-engineering", "fintech"],
    untCombinations: ["Математика + Информатика"],
    highlights: ["Доступная стоимость", "Огромный объём госгрантов", "Сертификация Cisco & Oracle", "Казахский/русский трек"],
    tuitionKzt: 1_479_000,
    tuitionLabel: "1 479 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    untGrant: 96,
    gpaMinimum: 2.8,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Высочайшая квота госгрантов МОН РК по группе B057 в стране",
    livingCostEstimateKzt: 160_000,
    applicationDeadlineEstimate: "до 20 июля 2027 (грант) / 20 августа (договор)",
    campusInfo: "Манаса/Жандосова, Алматы, студенческое общежитие в пешей доступности",
    employmentRate: "91% трудоустройство",
    reviews: [
      { author: "Нурсултан Е.", course: "3 курс IS", quote: "Отличный баланс цены и качества. Легко поступить на грант с ЕНТ около 100, при этом есть казахское отделение.", rating: 4.7 }
    ],
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика", description: "Порог 65 для платного, от 96 на грант", isMandatory: true },
      { label: "Аттестат об окончании школы/колледжа", description: "Оригинал", isMandatory: true },
    ],
    careerFocus: ["Финтех & Банки (Kaspi/Halyk)", "Стартапы & Astana Hub", "Удалёнка на США/Европу"],
    source: { label: "МУИТ — Бакалавриат", url: "https://iitu.edu.kz/ru/applicants/bachelor/" },
    dataNote: "Стоимость зафиксирована на 2026–2027 учебный год. IELTS не является строгим порогом.",
  },
  {
    id: "sdu-cs",
    university: "SDU University",
    shortName: "SDU",
    program: "Computer Science & Smart Systems",
    code: "6B06102",
    city: "Каскелен",
    duration: "4 года",
    language: "Английский",
    interests: ["computer-science", "ai-robotics", "software-engineering"],
    untCombinations: ["Математика + Информатика", "Математика + Физика"],
    highlights: ["Американский кампус закрытого типа", "Beta Career центр", "Олимпиада SPT с грантами до 100%", "35+ студенческих клубов"],
    tuitionKzt: 1_900_000,
    tuitionLabel: "≈ 1 900 000 ₸ / год",
    tuitionYear: "демо-оценка",
    tuitionConfidence: "demo",
    untPaid: 65,
    untGrant: 101,
    gpaMinimum: 3.0,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Собственная республиканская олимпиада SPT + государственные гранты МОН РК",
    livingCostEstimateKzt: 120_000,
    applicationDeadlineEstimate: "до 1 августа 2027",
    campusInfo: "Огромный современный кампус в Каскелене, спорткомплекс, студенческие общежития нового типа",
    employmentRate: "93% трудоустройство",
    reviews: [
      { author: "Аружан С.", course: "2 курс CS", quote: "Кампусная жизнь в SDU — лучшая в Казахстане. Все живут вместе, атмосфера как в американских фильмах.", rating: 4.9 }
    ],
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика", description: "Мин. 65 для договора", isMandatory: true },
      { label: "IELTS 5.5 или внутренний SDU Proficiency Test", description: "Бесплатная сдача в дни открытых дверей", isMandatory: true },
    ],
    careerFocus: ["Big Tech & Релокейт", "Стартапы & Astana Hub", "Удалёнка на США/Европу"],
    source: { label: "SDU — Admission", url: "https://sdu.edu.kz/en/admission-3-2/" },
  },
  {
    id: "nu-cs",
    university: "Nazarbayev University",
    shortName: "NU",
    program: "Computer Science & Robotics",
    code: "BSc CS",
    city: "Астана",
    duration: "4 года",
    language: "Английский",
    interests: ["computer-science", "ai-robotics", "data-science"],
    untCombinations: ["Математика + Информатика", "Математика + Физика"],
    highlights: ["Исследовательский университет мирового уровня", "Международный профессорско-преподавательский состав", "Грант «Өркен» покрывает 100%"],
    tuitionKzt: 7_350_000,
    tuitionLabel: "100% Грант «Өркен» / $15 000",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 85,
    untGrant: 125,
    gpaMinimum: 3.7,
    ielts: 6.5,
    scholarship: true,
    scholarshipDetails: "Государственный грант «Өркен» покрывает 100% стоимости обучения, проживание и повышенную стипендию",
    livingCostEstimateKzt: 200_000,
    applicationDeadlineEstimate: "Early: 30 ноября 2026, Regular: 30 марта 2027",
    campusInfo: "Кабанбай батыра 53, суперкомпьютерный кластер, лаборатории робототехники и геномики",
    employmentRate: "98% трудоустройство / зачисление в Stanford, MIT, CMU",
    acceptanceRateEstimate: "Очень селективно (приём ~12% от подавших)",
    reviews: [
      { author: "Ерлан Д.", course: "Выпускник NU", quote: "Академическая строгость на максимуме. Плагиат = отчисление. Но после NU открыты любые двери мира.", rating: 5.0 }
    ],
    requirementsChecklist: [
      { label: "IELTS 6.5+ (не ниже 6.0 в секциях)", description: "Строго обязательно для прямого поступления", isMandatory: true },
      { label: "SAT Reasoning Test или вступительный экзамен NUET", description: "Конкурсный отбор по математике", isMandatory: true },
      { label: "Мотивационное эссе (Personal Statement)", description: "500-800 слов на английском языке", isMandatory: true },
      { label: "2 рекомендации от преподавателей", description: "Математика / информатика", isMandatory: true },
    ],
    careerFocus: ["Big Tech & Релокейт", "Наука & R&D (ИИ лаборатории)", "Удалёнка на США/Европу"],
    source: { label: "NU — Regular Admissions", url: "https://nu.edu.kz/admissions" },
    dataNote: "Большинство студентов обучаются по 100% гранту «Өркен».",
  },
  {
    id: "satbayev-cs",
    university: "Satbayev University",
    shortName: "Satbayev",
    program: "Computer Engineering & Robotics",
    code: "6B06102",
    city: "Алматы",
    duration: "4 года",
    language: "Казахский / русский",
    interests: ["computer-science", "ai-robotics", "cloud-devops"],
    untCombinations: ["Математика + Физика", "Математика + Информатика"],
    highlights: ["Старейший инженерный флагман РК", "Инженерные лаборатории", "Казахское и русское отделения", "Доступное общежитие"],
    tuitionKzt: 1_600_000,
    tuitionLabel: "1 600 000 ₸ / год",
    tuitionYear: "2025–2026",
    tuitionConfidence: "previous-year",
    untPaid: 65,
    untGrant: 94,
    gpaMinimum: 2.8,
    scholarship: true,
    scholarshipDetails: "Более 1500 государственных грантов по техническим специальностям",
    livingCostEstimateKzt: 150_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Сатпаева/Байтурсынова, студенческий городок в центре Алматы",
    employmentRate: "89% трудоустройство в инженерные и IT компании",
    requirementsChecklist: [
      { label: "ЕНТ: Мат+Физ или Мат+Инф", description: "Порог 65 для договора, от 94 на грант", isMandatory: true },
      { label: "Аттестат", description: "Оригинал", isMandatory: true },
    ],
    careerFocus: ["Наука & R&D (ИИ лаборатории)", "Финтех & Банки (Kaspi/Halyk)"],
    source: { label: "Satbayev University", url: "https://satbayev.university" },
  },
  {
    id: "kimep-is",
    university: "KIMEP University",
    shortName: "КИМЭП",
    program: "Information Systems in Business & FinTech",
    code: "6B06101",
    city: "Алматы",
    duration: "4 года",
    language: "Английский",
    interests: ["fintech", "information-systems", "ui-ux-product"],
    untCombinations: ["Математика + Информатика", "Математика + География"],
    highlights: ["Синтез Бизнеса и IT", "Трудоустройство в Big 4 и FinTech", "Международная кредитная система"],
    tuitionKzt: 3_600_000,
    tuitionLabel: "≈ 3 600 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    gpaMinimum: 3.3,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Внутренние стипендии KIMEP за высокий балл ЕНТ/GPA до 100% покрытия",
    livingCostEstimateKzt: 220_000,
    applicationDeadlineEstimate: "до 10 июля 2027",
    campusInfo: "Абая/Достык, самый респектабельный район Алматы",
    employmentRate: "97% трудоустройство в финансовый и IT сектор",
    requirementsChecklist: [
      { label: "ЕНТ профильные предметы", description: "Порог 65", isMandatory: true },
      { label: "IELTS 5.5 или KEET", description: "KIMEP Entrance English Test", isMandatory: true },
    ],
    careerFocus: ["Финтех & Банки (Kaspi/Halyk)", "Стартапы & Astana Hub", "Big Tech & Релокейт"],
    source: { label: "KIMEP — Admissions", url: "https://kimep.kz/admissions/" },
  },
  {
    id: "kaznu-it",
    university: "Al-Farabi Kazakh National University",
    shortName: "КазНУ",
    program: "Information Systems & Cybersecurity",
    code: "6B06101",
    city: "Алматы",
    duration: "4 года",
    language: "Казахский / русский",
    interests: ["cybersecurity", "computer-science", "information-systems"],
    untCombinations: ["Математика + Информатика"],
    highlights: ["Топ-1 национальный университет РК", "Казгуград — зелёный кампус", "Мощная фундаментальная математика"],
    tuitionKzt: 1_350_000,
    tuitionLabel: "1 350 000 ₸ / год",
    tuitionYear: "2025–2026",
    tuitionConfidence: "previous-year",
    untPaid: 65,
    untGrant: 104,
    gpaMinimum: 2.8,
    scholarship: true,
    scholarshipDetails: "Крупнейший государственный грантовый пул в Казахстане",
    livingCostEstimateKzt: 140_000,
    applicationDeadlineEstimate: "до 20 июля 2027",
    campusInfo: "Казгуград, Ботанический сад, Дворец студентов, крупнейшая библиотека",
    employmentRate: "90% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика", description: "От 65 платно, от 104 на грант", isMandatory: true },
      { label: "Сертификат ЕНТ", description: "Электронный сертификат", isMandatory: true },
    ],
    careerFocus: ["Наука & R&D (ИИ лаборатории)", "Финтех & Банки (Kaspi/Halyk)", "Кибербезопасность & SOC"],
    source: { label: "КазНУ им. аль-Фараби", url: "https://welcome.kaznu.kz/" },
  },
  {
    id: "mnu-it",
    university: "Maqsut Narikbayev University (KAZGUU)",
    shortName: "MNU",
    program: "IT Product Management & LegalTech",
    code: "6B06104",
    city: "Астана",
    duration: "4 года",
    language: "Английский",
    interests: ["ui-ux-product", "fintech", "cybersecurity"],
    untCombinations: ["Математика + Информатика", "Математика + География"],
    highlights: ["IT Law & Compliance", "Product Management", "Комфортный кампус в Астане", "Тесная связь с государством и квазигоссектором"],
    tuitionKzt: 2_400_000,
    tuitionLabel: "2 400 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 70,
    untGrant: 101,
    gpaMinimum: 3.2,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Ректорские гранты и гранты МОН РК",
    livingCostEstimateKzt: 170_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Шоссе Коргалжын 8, Астана, европейский уровень аудиторий и коворкингов",
    employmentRate: "94% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика", description: "Порог 70", isMandatory: true },
      { label: "IELTS 5.5+ или внутренний тест MNU", description: "Подтверждение языка", isMandatory: true },
    ],
    careerFocus: ["Финтех & Банки (Kaspi/Halyk)", "Стартапы & Astana Hub"],
    source: { label: "MNU — Официальный портал", url: "https://mnu.kz/" },
  },
  {
    id: "kargu-it",
    university: "Karaganda Buketov University",
    shortName: "КарУ",
    program: "Software & Cloud Systems",
    code: "6B06101",
    city: "Караганда",
    duration: "4 года",
    language: "Казахский / русский",
    interests: ["software-engineering", "cloud-devops", "computer-science"],
    untCombinations: ["Математика + Информатика"],
    highlights: ["Крупнейший вуз Центрального Казахстана", "Низкая стоимость проживания", "Высокие шансы на грант"],
    tuitionKzt: 1_100_000,
    tuitionLabel: "1 100 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 60,
    untGrant: 88,
    gpaMinimum: 2.8,
    scholarship: true,
    scholarshipDetails: "Проходной балл на грант ниже столичных вузов (от 88 баллов)",
    livingCostEstimateKzt: 95_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Караганда, ул. Университетская 28, развитый городок общежитий",
    employmentRate: "88% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика", description: "От 60 баллов", isMandatory: true },
      { label: "Аттестат", description: "Оригинал", isMandatory: true },
    ],
    careerFocus: ["Финтех & Банки (Kaspi/Halyk)", "Удалёнка на США/Европу"],
    source: { label: "КарУ им. Букетова", url: "https://ksu.kz" },
  },
  {
    id: "auezov-it",
    university: "Auezov South Kazakhstan University",
    shortName: "ЮКУ",
    program: "Information Technologies & Robotics",
    code: "6B06101",
    city: "Шымкент",
    duration: "4 года",
    language: "Казахский / русский",
    interests: ["computer-science", "ai-robotics"],
    untCombinations: ["Математика + Информатика", "Математика + Физика"],
    highlights: ["Флагман южного региона Казахстана", "Доступная стоимость", "Теплая студенческая среда"],
    tuitionKzt: 1_050_000,
    tuitionLabel: "1 050 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 60,
    untGrant: 89,
    gpaMinimum: 2.8,
    scholarship: true,
    scholarshipDetails: "Квоты для южного региона и госгранты МОН РК",
    livingCostEstimateKzt: 85_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Шымкент, проспект Тауке хана 5, студенческий городок",
    employmentRate: "87% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика/Физика", description: "От 60 баллов", isMandatory: true },
    ],
    careerFocus: ["Стартапы & Astana Hub", "Финтех & Банки (Kaspi/Halyk)"],
    source: { label: "ЮКУ им. Ауэзова", url: "https://auezov.edu.kz" },
  },
  {
    id: "zhubanov-it",
    university: "Zhubanov Aktobe Regional University",
    shortName: "АРУ",
    program: "Computer Science & Data Engineering",
    code: "6B06101",
    city: "Актобе",
    duration: "4 года",
    language: "Казахский / русский",
    interests: ["computer-science", "data-science"],
    untCombinations: ["Математика + Информатика"],
    highlights: ["Главный университет Западного Казахстана", "Региональный IT-хаб Aktobe Hub"],
    tuitionKzt: 1_150_000,
    tuitionLabel: "1 150 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 60,
    untGrant: 87,
    gpaMinimum: 2.8,
    scholarship: true,
    scholarshipDetails: "Госгранты МОН РК + региональные акиматовские гранты",
    livingCostEstimateKzt: 90_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Актобе, ул. Бр. Жубановых 263",
    employmentRate: "86% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Информатика", description: "Порог 60 баллов", isMandatory: true },
    ],
    careerFocus: ["Финтех & Банки (Kaspi/Halyk)", "Удалёнка на США/Европу"],
    source: { label: "АРУ им. Жубанова", url: "https://zhubanov.edu.kz" },
  },
  // ================= MEDICINE & LIFE SCIENCES =================
  {
    id: "kaznmu-med",
    university: "Asfendiyarov Kazakh National Medical University",
    shortName: "КазНМУ им. Асфендиярова",
    program: "Общая медицина & Хирургия",
    code: "B086",
    city: "Алматы",
    country: "Казахстан",
    duration: "5 лет + 1 год интернатуры",
    language: "Казахский / русский",
    category: "medicine-health",
    interests: ["medicine-general"],
    untCombinations: ["Биология + Химия"],
    highlights: ["Главный медицинский университет Казахстана", "Университетские клинические базы", "Высочайшая квота грантов МОН и Минздрава РК"],
    tuitionKzt: 1_850_000,
    tuitionLabel: "1 850 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 70,
    untGrant: 116,
    gpaMinimum: 3.4,
    scholarship: true,
    scholarshipDetails: "Крупнейший государственный грантовый фонд Минздрава РК (по группе B086)",
    livingCostEstimateKzt: 150_000,
    applicationDeadlineEstimate: "до 20 июля 2027",
    campusInfo: "ул. Толе би 88, собственные клиники и симуляционные медицинские центры",
    employmentRate: "99% трудоустройство выпускников",
    acceptanceRateEstimate: "Высокий конкурс на грант (от 116 баллов)",
    reviews: [
      { author: "Айгерим С.", course: "4 курс Общей медицины", quote: "Учёба интенсивная с первого дня: анатомия, клиника, дежурства. Зато профессия врача на всю жизнь.", rating: 5.0 }
    ],
    requirementsChecklist: [
      { label: "ЕНТ: Биология + Химия", description: "Порог 70 для договора, от 116 на госгрант", isMandatory: true },
      { label: "Психометрический экзамен КазНМУ", description: "Обязательное тестирование на профпригодность", isMandatory: true },
      { label: "Медицинская справка 075/у", description: "Расширенное обследование и нарко/психо-диспансер", isMandatory: true },
    ],
    careerFocus: ["Медицина & Здравоохранение", "Наука & R&D (ИИ лаборатории)"],
    source: { label: "КазНМУ им. Асфендиярова", url: "https://kaznmu.edu.kz" },
  },
  {
    id: "amu-med",
    university: "Astana Medical University",
    shortName: "МУА",
    program: "Педиатрия & Лечебное дело",
    code: "B086",
    city: "Астана",
    country: "Казахстан",
    duration: "5 лет",
    language: "Казахский / русский",
    category: "medicine-health",
    interests: ["medicine-general", "biomedicine-pharma"],
    untCombinations: ["Биология + Химия"],
    highlights: ["Столичный медицинский хаб", "Сотрудничество с Национальными научными медцентрами Астаны", "Современный симуляционный госпиталь"],
    tuitionKzt: 1_750_000,
    tuitionLabel: "1 750 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 70,
    untGrant: 113,
    gpaMinimum: 3.2,
    scholarship: true,
    scholarshipDetails: "Госгранты Минздрава РК + акиматовские целевые гранты г. Астана",
    livingCostEstimateKzt: 170_000,
    applicationDeadlineEstimate: "до 20 июля 2027",
    campusInfo: "ул. Сарыарка 33, Астана, новые студенческие резиденции",
    employmentRate: "97% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Биология + Химия", description: "Мин. 70 для договора", isMandatory: true },
      { label: "Психометрическое тестирование", description: "Сдача в МУА", isMandatory: true },
    ],
    careerFocus: ["Медицина & Здравоохранение"],
    source: { label: "МУА — Официальный сайт", url: "https://amu.edu.kz" },
  },
  {
    id: "kaznmu-pharma",
    university: "Asfendiyarov Kazakh National Medical University",
    shortName: "КазНМУ",
    program: "Фармация & Биомедицинские технологии",
    code: "B087",
    city: "Алматы",
    country: "Казахстан",
    duration: "5 лет",
    language: "Казахский / русский",
    category: "medicine-health",
    interests: ["biomedicine-pharma", "dentistry"],
    untCombinations: ["Биология + Химия"],
    highlights: ["Разработка лекарственных препаратов", "Фармацевтический инжиниринг", "Партнёрство с фармгигантами Santo и Nobel"],
    tuitionKzt: 1_650_000,
    tuitionLabel: "1 650 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    untGrant: 106,
    gpaMinimum: 3.1,
    scholarship: true,
    scholarshipDetails: "Госгранты МОН и корпоративные стипендии фармацевтических заводов",
    livingCostEstimateKzt: 150_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Алматы, фармацевтические лаборатории стандарта GMP",
    employmentRate: "94% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Биология + Химия", description: "Порог 65 баллов", isMandatory: true },
    ],
    careerFocus: ["Медицина & Здравоохранение", "Наука & R&D (ИИ лаборатории)"],
    source: { label: "КазНМУ — Фармация", url: "https://kaznmu.edu.kz" },
  },

  // ================= BUSINESS, FINANCE & MANAGEMENT =================
  {
    id: "kimep-finance",
    university: "KIMEP University",
    shortName: "КИМЭП",
    program: "Finance, Accounting & Investment Banking",
    code: "6B04101",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Английский",
    category: "business-finance",
    interests: ["finance-fintech", "fintech", "economics"],
    untCombinations: ["Математика + География"],
    highlights: ["Топ-1 бизнес-школа Центральной Азии", "Аккредитация AFBE / AACSB pathway", "Прямой поток в Big 4, Kaspi, Halyk и инвестфонды"],
    tuitionKzt: 3_800_000,
    tuitionLabel: "≈ 3 800 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    gpaMinimum: 3.4,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Собственные гранты KIMEP Президента университета (покрытие 100% за высокий ЕНТ/GPA)",
    livingCostEstimateKzt: 220_000,
    applicationDeadlineEstimate: "до 15 июля 2027",
    campusInfo: "Абая/Достык, самый живописный кампус в сердце Алматы",
    employmentRate: "98% трудоустройство с зарплатами выше рынка",
    acceptanceRateEstimate: "Высокая селективность, входной английский KEET/IELTS",
    reviews: [
      { author: "Тимур А.", course: "3 курс Finance", quote: "КИМЭП учит мыслить на глобальном уровне. Преподают профессора из США и Великобритании, кейс-метод Гарварда.", rating: 5.0 }
    ],
    requirementsChecklist: [
      { label: "ЕНТ: Математика + География", description: "Мин. 65 баллов", isMandatory: true },
      { label: "IELTS 5.5+ или KEET", description: "Внутренний тест английского KIMEP", isMandatory: true },
    ],
    careerFocus: ["Финтех & Банки (Kaspi/Halyk)", "Корпоративный сектор & Big 4", "Стартапы & Предпринимательство"],
    source: { label: "KIMEP — Bang College of Business", url: "https://kimep.kz" },
  },
  {
    id: "almau-mgmt",
    university: "Almaty Management University",
    shortName: "AlmaU",
    program: "International Management & Entrepreneurship",
    code: "6B04102",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Казахский / русский",
    category: "business-finance",
    interests: ["business-mgmt", "marketing-digital"],
    untCombinations: ["Математика + География"],
    highlights: ["Первая бизнес-школа Казахстана (ранее МАБ)", "Инкубатор стартапов AlmaU Incubator", "Двойные дипломы с вузами Франции и Швейцарии"],
    tuitionKzt: 2_100_000,
    tuitionLabel: "2 100 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 60,
    untGrant: 98,
    gpaMinimum: 3.0,
    scholarship: true,
    scholarshipDetails: "Гранты МОН РК по экономическим специальностям и ректорские скидки до 50%",
    livingCostEstimateKzt: 160_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "ул. Розыбакиева 227, Алматы, современный бизнес-хаб и медиа-лаборатории",
    employmentRate: "93% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + География", description: "От 60 баллов", isMandatory: true },
      { label: "Мотивационное интервью AlmaU", description: "Собеседование по лидерству", isMandatory: false },
    ],
    careerFocus: ["Стартапы & Предпринимательство", "Корпоративный сектор & Big 4"],
    source: { label: "AlmaU — Бакалавриат", url: "https://almau.edu.kz" },
  },
  {
    id: "kbtu-ise",
    university: "Kazakh-British Technical University",
    shortName: "КБТУ (МИЭ)",
    program: "Economics & Data Analytics (London School of Economics Program)",
    code: "6B04103",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Английский",
    category: "business-finance",
    interests: ["economics", "finance-fintech", "data-science"],
    untCombinations: ["Математика + География", "Математика + Информатика"],
    highlights: ["Диплом Университета Лондона (University of London / LSE)", "Синтез эконометрики, Python и макроаналитики", "Выпускники работают в JP Morgan, Morgan Stanley, Bloomberg"],
    tuitionKzt: 3_200_000,
    tuitionLabel: "≈ 3 200 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 75,
    untGrant: 114,
    gpaMinimum: 3.5,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Гранты МОН РК и корпоративные гранты Национального Банка РК / Halyk",
    livingCostEstimateKzt: 200_000,
    applicationDeadlineEstimate: "до 15 июля 2027",
    campusInfo: "Толе би 59, Алматы, доступ к терминалам Bloomberg",
    employmentRate: "97% международное трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Мат+Гео или Мат+Инф", description: "От 75 для договора, от 114 на грант", isMandatory: true },
      { label: "IELTS 5.5+", description: "Официальный сертификат", isMandatory: true },
    ],
    careerFocus: ["Финтех & Банки (Kaspi/Halyk)", "Корпоративный сектор & Big 4", "Удалёнка на США/Европу"],
    source: { label: "КБТУ — МИЭ", url: "https://kbtu.edu.kz" },
  },

  // ================= LAW & SOCIAL SCIENCES =================
  {
    id: "mnu-law",
    university: "Maqsut Narikbayev University (KAZGUU)",
    shortName: "MNU (КАЗГЮУ)",
    program: "Международное право & Корпоративная юриспруденция",
    code: "6B04201",
    city: "Астана",
    country: "Казахстан",
    duration: "4 года",
    language: "Английский",
    category: "law-social",
    interests: ["law-jurisprudence", "international-relations"],
    untCombinations: ["Всемирная история + Основы права", "Иностранный язык + Всемирная история"],
    highlights: ["Главная юридическая школа страны", "Аккредитация FIBAA (Германия)", "Судебный зал заседаний Moot Court, связи с Верховным судом и МФЦА (AIFC)"],
    tuitionKzt: 2_600_000,
    tuitionLabel: "2 600 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 75,
    untGrant: 118,
    gpaMinimum: 3.4,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Госгранты МОН РК по группе B049 и ректорские гранты им. Нарикбаева",
    livingCostEstimateKzt: 180_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Коргалжынское шоссе 8, Астана, европейский кампус с международной юридической библиотекой",
    employmentRate: "96% трудоустройство в госорганы, международные юрфирмы (White & Case, Dentons) и МФЦА",
    reviews: [
      { author: "Алишер К.", course: "4 курс Международного права", quote: "В КАЗГЮУ учат практическому праву: дебаты, кейс-чемпионаты, судебные процессы на английском.", rating: 5.0 }
    ],
    requirementsChecklist: [
      { label: "ЕНТ: История + Право/Иностр. яз", description: "Порог 75, грант от 118", isMandatory: true },
      { label: "IELTS 5.5+ или экзамен MNU", description: "Внутренний тест", isMandatory: true },
    ],
    careerFocus: ["Юриспруденция & Международное право", "Корпоративный сектор & Big 4"],
    source: { label: "MNU — Высшая школа права", url: "https://mnu.kz" },
  },
  {
    id: "kaznu-ir",
    university: "Al-Farabi Kazakh National University",
    shortName: "КазНУ им. аль-Фараби",
    program: "Международные отношения & Дипломатическая служба",
    code: "6B03101",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Казахский / русский",
    category: "law-social",
    interests: ["international-relations", "law-jurisprudence"],
    untCombinations: ["Иностранный язык + Всемирная история"],
    highlights: ["Кузница казахстанской дипломатии и послов РК", "Изучение 2 иностранных языков (ООН)", "Стажировки в МИД РК и международных организациях"],
    tuitionKzt: 1_500_000,
    tuitionLabel: "1 500 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    untGrant: 120,
    gpaMinimum: 3.2,
    scholarship: true,
    scholarshipDetails: "Квоты МОН РК для будущих дипломатов",
    livingCostEstimateKzt: 140_000,
    applicationDeadlineEstimate: "до 20 июля 2027",
    campusInfo: "Факультет международных отношений, Казгуград",
    employmentRate: "91% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Иностр. яз + Всемирная история", description: "Порог 65, грант от 120", isMandatory: true },
    ],
    careerFocus: ["Юриспруденция & Международное право", "Корпоративный сектор & Big 4"],
    source: { label: "КазНУ — МО", url: "https://welcome.kaznu.kz" },
  },
  {
    id: "kaznu-psych",
    university: "Al-Farabi Kazakh National University",
    shortName: "КазНУ",
    program: "Практическая психология & Организационный HR-консалтинг",
    code: "6B03102",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Казахский / русский",
    category: "law-social",
    interests: ["psychology-hr"],
    untCombinations: ["Биология + География", "Биология + Химия"],
    highlights: ["Психологическая диагностика и коучинг", "HR-аналитика для крупных компаний", "Психологический центр поддержки студентов"],
    tuitionKzt: 1_350_000,
    tuitionLabel: "1 350 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 60,
    untGrant: 104,
    gpaMinimum: 2.9,
    scholarship: true,
    scholarshipDetails: "Госгранты МОН РК по группе B029",
    livingCostEstimateKzt: 140_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Казгуград, Алматы",
    employmentRate: "89% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Биология + География/Химия", description: "От 60 баллов", isMandatory: true },
    ],
    careerFocus: ["Корпоративный сектор & Big 4", "Медицина & Здравоохранение"],
    source: { label: "КазНУ — Психология", url: "https://welcome.kaznu.kz" },
  },

  // ================= ENGINEERING & TECH =================
  {
    id: "satbayev-petro",
    university: "Satbayev University",
    shortName: "Satbayev University",
    program: "Нефтегазовая инженерия & Геология (Petroleum Engineering)",
    code: "6B07201",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Казахский / русский",
    category: "engineering",
    interests: ["petroleum-mining", "engineering-tech"],
    untCombinations: ["Математика + Физика"],
    highlights: ["Прямое трудоустройство в ТШО (TCO), NCOC, КазМунайГаз", "Собственный буровой симулятор и петрофизические лаборатории", "Высочайшие стартовые оклады в индустрии"],
    tuitionKzt: 1_650_000,
    tuitionLabel: "1 650 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    untGrant: 95,
    gpaMinimum: 3.0,
    scholarship: true,
    scholarshipDetails: "Крупная государственная квота грантов МОН РК по горно-нефтяному сектору",
    livingCostEstimateKzt: 150_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Сатпаева 22, Алматы, студенческие общежития в центре города",
    employmentRate: "95% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Физика", description: "Порог 65 для договора, от 95 на грант", isMandatory: true },
    ],
    careerFocus: ["Корпоративный сектор & Big 4", "Наука & R&D (ИИ лаборатории)"],
    source: { label: "Satbayev — Нефтегазовый инжиниринг", url: "https://satbayev.university" },
  },
  {
    id: "satbayev-robotics",
    university: "Satbayev University",
    shortName: "Satbayev University",
    program: "Мехатроника, Робототехника & Автоматизация",
    code: "6B07103",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Казахский / русский",
    category: "engineering",
    interests: ["robotics-mechatronics", "engineering-tech", "ai-robotics"],
    untCombinations: ["Математика + Физика", "Математика + Информатика"],
    highlights: ["Лаборатория промышленных манипуляторов KUKA и Festo", "Создание дронов, мобильных роботов и IoT устройств", "Участие в международных RoboSub и хакатонах"],
    tuitionKzt: 1_650_000,
    tuitionLabel: "1 650 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    untGrant: 98,
    gpaMinimum: 3.0,
    scholarship: true,
    scholarshipDetails: "Высокая квота госгрантов по группе B064 (Механика и металлообработка)",
    livingCostEstimateKzt: 150_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "Сатпаева 22, Алматы, Фаблаб и лаборатория мехатроники",
    employmentRate: "93% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Физика/Информатика", description: "От 65 баллов", isMandatory: true },
    ],
    careerFocus: ["Наука & R&D (ИИ лаборатории)", "Стартапы & Предпринимательство"],
    source: { label: "Satbayev — Мехатроника", url: "https://satbayev.university" },
  },
  {
    id: "kazgasa-arch",
    university: "Kazakh Leading Academy of Architecture and Civil Engineering",
    shortName: "КазГАСА",
    program: "Архитектура & Градостроительное проектирование",
    code: "6B07301",
    city: "Алматы",
    country: "Казахстан",
    duration: "5 лет",
    language: "Казахский / русский",
    category: "engineering",
    interests: ["architecture-civil", "design-multimedia"],
    untCombinations: ["Творческий экзамен", "Математика + Физика"],
    highlights: ["Главный архитектурный институт РК", "BIM-моделирование (Revit, ArchiCAD, Rhino)", "Практика в BI Group, Bazis-A и зарубежных бюро"],
    tuitionKzt: 1_750_000,
    tuitionLabel: "1 750 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    untGrant: 108,
    gpaMinimum: 3.1,
    scholarship: true,
    scholarshipDetails: "Госгранты МОН РК по группе B073",
    livingCostEstimateKzt: 160_000,
    applicationDeadlineEstimate: "Творческие экзамены: с 20 июня по 7 июля 2027",
    campusInfo: "ул. Рыскулбекова 28, Алматы, архитектурные мастерские и макетные цеха",
    employmentRate: "94% трудоустройство",
    requirementsChecklist: [
      { label: "Творческие экзамены (Рисунок и Чертёж)", description: "Сдача очно в приемной комиссии КазГАСА", isMandatory: true },
      { label: "ЕНТ: Грамотность чтения + История Казахстана", description: "Базовые обязательные предметы ЕНТ", isMandatory: true },
    ],
    careerFocus: ["Креативные индустрии & Дизайн", "Стартапы & Предпринимательство"],
    source: { label: "КазГАСА — Архитектурный факультет", url: "https://kazgasa.kz" },
  },

  // ================= DESIGN, MEDIA & ARTS =================
  {
    id: "kazgasa-design",
    university: "Kazakh Leading Academy of Architecture and Civil Engineering",
    shortName: "КазГАСА",
    program: "Графический & Digital UI/UX дизайн",
    code: "6B02101",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Казахский / русский",
    category: "design-creative",
    interests: ["design-multimedia", "ui-ux-product"],
    untCombinations: ["Творческий экзамен"],
    highlights: ["Брендинг, моушн-дизайн, интерфейсы мобильных приложений", "Выпускные портфолио уровня международных дизайн-агентств", "Партнёрство с креативными хабами"],
    tuitionKzt: 1_700_000,
    tuitionLabel: "1 700 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    untGrant: 107,
    gpaMinimum: 3.0,
    scholarship: true,
    scholarshipDetails: "Госгранты МОН РК по группе B031 (Дизайн)",
    livingCostEstimateKzt: 160_000,
    applicationDeadlineEstimate: "Творческие экзамены до 7 июля",
    campusInfo: "Дизайн-лаборатории Mac и фотостудии КазГАСА",
    employmentRate: "92% трудоустройство",
    requirementsChecklist: [
      { label: "Сдача творческих экзаменов (Рисунок / Композиция)", description: "Оценка художественного портфолио", isMandatory: true },
    ],
    careerFocus: ["Креативные индустрии & Дизайн", "Геймдев & Креатив", "Удалёнка на США/Европу"],
    source: { label: "КазГАСА — Дизайн", url: "https://kazgasa.kz" },
  },
  {
    id: "almau-media",
    university: "Almaty Management University",
    shortName: "AlmaU",
    program: "Digital Journalism, Media Production & PR",
    code: "6B03201",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Казахский / русский",
    category: "design-creative",
    interests: ["journalism-media", "marketing-digital"],
    untCombinations: ["Творческий экзамен", "Иностранный язык + Всемирная история"],
    highlights: ["AlmaU Media Center: профессиональная ТВ- и подкаст-студия", "Создание цифрового медиа-контента, SMM, PR и сторителлинг", "Спикеры — ведущие медиаменеджеры РК"],
    tuitionKzt: 1_950_000,
    tuitionLabel: "1 950 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 60,
    untGrant: 104,
    gpaMinimum: 2.9,
    scholarship: true,
    scholarshipDetails: "Гранты МОН РК и стипендии медиа-холдингов",
    livingCostEstimateKzt: 160_000,
    applicationDeadlineEstimate: "до 20 июля 2027",
    campusInfo: "Медиацентр AlmaU, монтажные станции и хромакей-павильоны",
    employmentRate: "91% трудоустройство",
    requirementsChecklist: [
      { label: "Творческое эссе или ЕНТ профиль", description: "Проверка авторского слога", isMandatory: true },
    ],
    careerFocus: ["Креативные индустрии & Дизайн", "Стартапы & Предпринимательство"],
    source: { label: "AlmaU — Школа медиа", url: "https://almau.edu.kz" },
  },

  // ================= NATURAL SCIENCES & MATH =================
  {
    id: "nu-bio",
    university: "Nazarbayev University",
    shortName: "NU",
    program: "Biological Sciences & Biomedical Research",
    code: "BSc Bio",
    city: "Астана",
    country: "Казахстан",
    duration: "4 года",
    language: "Английский",
    category: "natural-sciences",
    interests: ["biomedicine-pharma", "biotech-chemistry"],
    untCombinations: ["Биология + Химия"],
    highlights: ["Исследования стволовых клеток и биоинженерия", "100% грант «Өркен»", "Прямой трек в зарубежную магистратуру и NU School of Medicine"],
    tuitionKzt: 7_350_000,
    tuitionLabel: "100% Грант «Өркен»",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 85,
    untGrant: 124,
    gpaMinimum: 3.7,
    ielts: 6.5,
    scholarship: true,
    scholarshipDetails: "Полный госгрант «Өркен» с бесплатным проживанием в кампусе Астаны",
    livingCostEstimateKzt: 200_000,
    applicationDeadlineEstimate: "до 30 марта 2027",
    campusInfo: "Кабанбай батыра 53, Астана, геномные и биомолекулярные лаборатории",
    employmentRate: "97% трудоустройство и PhD за рубежом",
    acceptanceRateEstimate: "Высокая селективность",
    requirementsChecklist: [
      { label: "IELTS 6.5+", description: "Не ниже 6.0 в секциях", isMandatory: true },
      { label: "SAT или тест NUET", description: "Математика и естественные науки", isMandatory: true },
    ],
    careerFocus: ["Наука & R&D (ИИ лаборатории)", "Медицина & Здравоохранение"],
    source: { label: "NU — School of Sciences and Humanities", url: "https://nu.edu.kz" },
  },
  {
    id: "kaznu-math",
    university: "Al-Farabi Kazakh National University",
    shortName: "КазНУ",
    program: "Прикладная математика & Анализ данных",
    code: "6B05401",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Казахский / русский",
    category: "natural-sciences",
    interests: ["applied-math", "data-science"],
    untCombinations: ["Математика + Физика", "Математика + Информатика"],
    highlights: ["Сильнейшая математическая школа Центральной Азии", "Суперкомпьютерный центр КазНУ", "Подготовка квантов, исследователей и аналитиков алгоритмов"],
    tuitionKzt: 1_350_000,
    tuitionLabel: "1 350 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    untGrant: 97,
    gpaMinimum: 3.0,
    scholarship: true,
    scholarshipDetails: "Сотни государственных грантов МОН РК по группе Математика и статистика",
    livingCostEstimateKzt: 140_000,
    applicationDeadlineEstimate: "до 20 июля 2027",
    campusInfo: "Мехмат КазНУ, Казгуград",
    employmentRate: "93% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Математика + Физика/Информатика", description: "Порог 65", isMandatory: true },
    ],
    careerFocus: ["Наука & R&D (ИИ лаборатории)", "Финтех & Банки (Kaspi/Halyk)"],
    source: { label: "КазНУ — Мехмат", url: "https://welcome.kaznu.kz" },
  },

  // ================= LANGUAGES & EDUCATION =================
  {
    id: "kazumo-translation",
    university: "Kazakh Ablai Khan University of International Relations and World Languages",
    shortName: "КазУМОиМЯ им. Абылай хана",
    program: "Синхронный и письменный перевод (English & Chinese)",
    code: "6B02301",
    city: "Алматы",
    country: "Казахстан",
    duration: "4 года",
    language: "Английский",
    category: "languages-pedagogy",
    interests: ["linguistics-translation", "international-relations"],
    untCombinations: ["Иностранный язык + Всемирная история"],
    highlights: ["Флагман лингвистического образования Казахстана", "Кабинеты синхронного перевода", "Стажировки в посольствах, ООН и международных корпорациях"],
    tuitionKzt: 1_400_000,
    tuitionLabel: "1 400 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 65,
    untGrant: 115,
    gpaMinimum: 3.1,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    scholarshipDetails: "Государственные образовательные гранты МОН РК по языковым группам",
    livingCostEstimateKzt: 150_000,
    applicationDeadlineEstimate: "до 25 июля 2027",
    campusInfo: "ул. Муратбаева 200, Алматы",
    employmentRate: "92% трудоустройство",
    requirementsChecklist: [
      { label: "ЕНТ: Английский язык + Всемирная история", description: "Мин. 65 для договора, от 115 на грант", isMandatory: true },
    ],
    careerFocus: ["Корпоративный сектор & Big 4", "Юриспруденция & Международное право"],
    source: { label: "КазУМОиМЯ — Переводческий факультет", url: "https://ablaikhan.kz" },
  },

  // ================= INTERNATIONAL BENCHMARKS (GERMANY & EUROPE) =================
  {
    id: "tum-engineering",
    university: "Technical University of Munich (TUM)",
    shortName: "TUM (Германия)",
    program: "Engineering, Informatics & Robotics",
    code: "TUM-BSc",
    city: "Мюнхен (Германия)",
    country: "Германия",
    duration: "3 года",
    language: "Английский",
    category: "engineering",
    interests: ["engineering-tech", "computer-science", "robotics-mechatronics"],
    untCombinations: ["Математика + Физика", "Математика + Информатика"],
    highlights: ["Топ-1 технический университет Германии", "Прямые связи с BMW, Siemens, Airbus", "Символическая стоимость обучения в государственном вузе ФРГ"],
    tuitionKzt: 1_500_000,
    tuitionLabel: "≈ €2 000 – €3 000 / год (госвуз ФРГ)",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    gpaMinimum: 3.8,
    ielts: 6.5,
    scholarship: true,
    scholarshipDetails: "DAAD стипендии и государственная субсидия высшего образования Германии",
    livingCostEstimateKzt: 450_000,
    applicationDeadlineEstimate: "до 15 июля 2027 через Uni-Assist",
    campusInfo: "Garching Campus, Мюнхен, передовые лаборатории аэрокосмических систем и ИИ",
    employmentRate: "99% глобальное трудоустройство в ЕС и США",
    acceptanceRateEstimate: "Селективный отбор по GPA и мотивационному письму",
    reviews: [
      { author: "Дастан Н.", course: "Выпускник TUM", quote: "Немецкая инженерная школа — эталон. За 3 года прокачиваешься так, что берут в любой европейский технологический гигант.", rating: 5.0 }
    ],
    requirementsChecklist: [
      { label: "Аттестат с GPA от 3.8 / 4.0", description: "Нотариальный перевод и апостиль", isMandatory: true },
      { label: "IELTS 6.5+ (или TestDaF при немецком треке)", description: "Сертификат знания языка", isMandatory: true },
      { label: "Мотивационное письмо (Motivation Letter)", description: "На английском языке", isMandatory: true },
    ],
    careerFocus: ["Big Tech & Релокейт", "Наука & R&D (ИИ лаборатории)", "Удалёнка на США/Европу"],
    source: { label: "TUM — International Bachelor", url: "https://www.tum.de" },
  },
  {
    id: "bocconi-biz",
    university: "Bocconi University",
    shortName: "Bocconi (Италия)",
    program: "International Economics & Management",
    code: "BOC-BSc",
    city: "Милан (Италия)",
    country: "Италия",
    duration: "3 года",
    language: "Английский",
    category: "business-finance",
    interests: ["finance-fintech", "economics", "business-mgmt"],
    untCombinations: ["Математика + География", "Математика + Информатика"],
    highlights: ["Топ-3 бизнес-университет Европы", "Карьерный трамплин в Лондонский Сити, McKinsey, Goldman Sachs", "Кампус в центре мировой столицы моды и финансов Милане"],
    tuitionKzt: 7_800_000,
    tuitionLabel: "≈ €15 000 / год (стипендии ISU до 100%)",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    gpaMinimum: 3.7,
    ielts: 6.5,
    satRequirement: 1350,
    scholarship: true,
    scholarshipDetails: "Need-based стипендии Bocconi ISU Scholarship (покрытие 100% обучения + бесплатное питание и жилье)",
    livingCostEstimateKzt: 480_000,
    applicationDeadlineEstimate: "Early: ноябрь, Spring: апрель 2027",
    campusInfo: "Милан, ультрасовременный кампус по проекту SANAA",
    employmentRate: "98% трудоустройство",
    requirementsChecklist: [
      { label: "Bocconi Test или SAT (1350+)", description: "Стандартизированный отбор", isMandatory: true },
      { label: "IELTS 6.5+", description: "Подтверждение английского языка", isMandatory: true },
    ],
    careerFocus: ["Корпоративный сектор & Big 4", "Финтех & Банки (Kaspi/Halyk)", "Big Tech & Релокейт"],
    source: { label: "Bocconi University — Undergraduate", url: "https://www.unibocconi.eu" },
  }
];

