import type { Program } from "./types";

export const programs: Program[] = [
  {
    id: "aitu-cs",
    university: "Astana IT University",
    shortName: "AITU",
    program: "Computer Science",
    code: "6B06101",
    city: "Астана",
    duration: "3 года",
    language: "Английский",
    interests: ["computer-science", "software-engineering", "data-science"],
    highlights: ["Machine Learning", "Web services", "3-летняя программа"],
    tuitionKzt: 2_500_000,
    tuitionLabel: "2 500 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 80,
    untGrant: 100,
    alternativeEnglishExam: true,
    scholarship: true,
    careerFocus: ["Практика", "Стартапы"],
    source: {
      label: "AITU — Bachelor’s Degree",
      url: "https://astanait.edu.kz/en/bachelor",
    },
    requirementsSource: {
      label: "AITU — Computer Science",
      url: "https://astanait.edu.kz/Computer-Science-bachelor",
    },
    dataNote: "Порог на грант — 100. Для платного обучения указан порог ЕНТ 80 и AET.",
  },
  {
    id: "aitu-big-data",
    university: "Astana IT University",
    shortName: "AITU",
    program: "Big Data Analysis",
    code: "6B06103",
    city: "Астана",
    duration: "3 года",
    language: "Английский",
    interests: ["data-science", "computer-science"],
    highlights: ["Data Analytics", "Machine Learning", "Applied mathematics"],
    tuitionKzt: 2_500_000,
    tuitionLabel: "2 500 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 80,
    alternativeEnglishExam: true,
    scholarship: true,
    careerFocus: ["Практика", "Исследования"],
    source: { label: "AITU — Bachelor’s Degree", url: "https://astanait.edu.kz/en/bachelor" },
    dataNote: "Программа и стоимость опубликованы AITU; требования зависят от траектории поступления.",
  },
  {
    id: "aitu-cyber",
    university: "Astana IT University",
    shortName: "AITU",
    program: "Cybersecurity",
    code: "6B06301",
    city: "Астана",
    duration: "3 года",
    language: "Английский",
    interests: ["cybersecurity", "computer-science"],
    highlights: ["Cyber labs", "Network security", "IT vendors"],
    tuitionKzt: 2_500_000,
    tuitionLabel: "2 500 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 80,
    alternativeEnglishExam: true,
    scholarship: true,
    careerFocus: ["Практика"],
    source: { label: "AITU — Bachelor’s Degree", url: "https://astanait.edu.kz/en/bachelor" },
  },
  {
    id: "aitu-se",
    university: "Astana IT University",
    shortName: "AITU",
    program: "Software Engineering",
    code: "6B06102",
    city: "Астана",
    duration: "3 года",
    language: "Английский",
    interests: ["software-engineering", "computer-science"],
    highlights: ["Product development", "Team projects", "Startup community"],
    tuitionKzt: 2_500_000,
    tuitionLabel: "2 500 000 ₸ / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 80,
    alternativeEnglishExam: true,
    scholarship: true,
    careerFocus: ["Практика", "Стартапы"],
    source: { label: "AITU — Bachelor’s Degree", url: "https://astanait.edu.kz/en/bachelor" },
  },
  {
    id: "iitu-is",
    university: "International Information Technology University",
    shortName: "IITU",
    program: "Information Systems",
    code: "B057",
    city: "Алматы",
    duration: "4 года",
    language: "Английский",
    interests: ["computer-science", "software-engineering"],
    highlights: ["Information systems", "English placement test", "Алматы"],
    tuitionKzt: 1_479_000,
    tuitionLabel: "1 479 000 ₸ / 1 курс",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    alternativeEnglishExam: true,
    scholarship: true,
    careerFocus: ["Практика"],
    source: { label: "IITU — Бакалавриат", url: "https://iitu.edu.kz/ru/applicants/bachelor/" },
    dataNote: "Стоимость указана для группы B057. IELTS можно заменить внутренним экзаменом.",
  },
  {
    id: "iitu-cyber",
    university: "International Information Technology University",
    shortName: "IITU",
    program: "Information Security",
    code: "B058",
    city: "Алматы",
    duration: "4 года",
    language: "Английский",
    interests: ["cybersecurity", "computer-science"],
    highlights: ["Information security", "English placement test", "4-летняя база"],
    tuitionKzt: 1_479_000,
    tuitionLabel: "1 479 000 ₸ / 1 курс",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    alternativeEnglishExam: true,
    scholarship: true,
    careerFocus: ["Практика"],
    source: { label: "IITU — Бакалавриат", url: "https://iitu.edu.kz/ru/applicants/bachelor/" },
    dataNote: "Стоимость опубликована для группы B058 на 2026–2027 учебный год.",
  },
  {
    id: "kbtu-is",
    university: "Kazakh-British Technical University",
    shortName: "KBTU",
    program: "Information Systems",
    code: "6B06101",
    city: "Алматы",
    duration: "4 года",
    language: "Английский",
    interests: ["computer-science", "software-engineering", "data-science"],
    highlights: ["IELTS 5.5", "Industry focus", "English-medium"],
    tuitionKzt: 2_800_000,
    tuitionLabel: "≈ 2 800 000 ₸ / год",
    tuitionYear: "демо-оценка",
    tuitionConfidence: "demo",
    untPaid: 50,
    untGrant: 110,
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    careerFocus: ["Практика", "Стартапы"],
    source: {
      label: "KBTU — Information Systems",
      url: "https://kbtu.edu.kz/ru/shkoly/shkola-informatsionnykh-tekhnologij-i-inzhenerii/bakalavriat-shkoly-informatsionnykh-tekhnologij",
    },
    dataNote: "Требования подтверждены. Стоимость — демонстрационная оценка и не считается официальной.",
  },
  {
    id: "satbayev-cs",
    university: "Satbayev University",
    shortName: "Satbayev",
    program: "Computer Science",
    code: "6B06102",
    city: "Алматы",
    duration: "4 года",
    language: "Смешанный",
    interests: ["computer-science", "software-engineering", "data-science"],
    highlights: ["Engineering ecosystem", "Research labs", "Strong technical base"],
    tuitionKzt: 1_600_000,
    tuitionLabel: "1 600 000 ₸ / год",
    tuitionYear: "2025–2026",
    tuitionConfidence: "previous-year",
    scholarship: true,
    careerFocus: ["Исследования", "Практика"],
    source: {
      label: "Satbayev — тарифы 2025–2026",
      url: "https://official.satbayev.university/download/document/47247/Tuition%20Fees%20for%20Bachelor%27s%20Programs%20for%20Legal%20Entities%20for%20the%202025%EF%BF%BD2026.pdf",
    },
    dataNote: "Стоимость относится к прошлому учебному году и требует проверки перед подачей.",
  },
  {
    id: "sdu-cs",
    university: "SDU University",
    shortName: "SDU",
    program: "Computer Science",
    code: "6B06102",
    city: "Каскелен",
    duration: "4 года",
    language: "Английский",
    interests: ["computer-science", "software-engineering", "data-science"],
    highlights: ["English-medium", "35+ student clubs", "Beta Career"],
    tuitionKzt: 1_900_000,
    tuitionLabel: "≈ 1 900 000 ₸ / год",
    tuitionYear: "демо-оценка",
    tuitionConfidence: "demo",
    ielts: 5.5,
    alternativeEnglishExam: true,
    scholarship: true,
    careerFocus: ["Практика", "Стартапы"],
    source: { label: "SDU — Admission", url: "https://sdu.edu.kz/en/admission-3-2/" },
    dataNote: "IELTS 5.5 подтверждён. Стоимость в прототипе демонстрационная; официальный тариф вынесен в источник.",
  },
  {
    id: "nu-cs",
    university: "Nazarbayev University",
    shortName: "NU",
    program: "Computer Science",
    code: "BSc CS",
    city: "Астана",
    duration: "4 года",
    language: "Английский",
    interests: ["computer-science", "data-science", "software-engineering"],
    highlights: ["Research university", "English-medium", "International faculty"],
    tuitionKzt: 7_350_000,
    tuitionLabel: "$15 000 / год",
    tuitionYear: "2026–2027",
    tuitionConfidence: "verified",
    untPaid: 85,
    gpaMinimum: 4,
    ielts: 6,
    scholarship: true,
    careerFocus: ["Исследования", "Стартапы"],
    source: {
      label: "NU — Regular Admissions",
      url: "https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/",
    },
    dataNote: "Официальная стоимость — $15 000. Для сравнения бюджета использован ориентир 490 ₸/$.",
  },
];
